"""``ScalarSpec``, ``ScalarRegistry`` and the built-in scalar fakes (B7, C42).

One spec type describes a custom scalar for every use the package makes of it:
``fake`` builds a factory value, ``serialize`` turns a Python value into JSON
for variables, and ``parse`` turns JSON into a Python value for responses. The
default ``parse=None`` leaves the raw JSON in place, so the raw response is
never lost.

``ScalarRegistry`` is the one place specs are kept. Response decoding reads it
through :meth:`ScalarRegistry.parsers`, which is the ``name -> parse`` mapping
the response materializer already accepts, so no second registry exists.

The five scalars the GraphQL specification defines are not custom, are never
registered, and take their fake from ``BUILTIN_FAKES``. Their values are part
of the determinism promise and are pinned by ``tests/factory/golden.json``:

- ``String``: 8 characters from ``DEFAULT_ALPHABET``.
- ``ID``: 12 lowercase hexadecimal characters.
- ``Int``: an integer from 1 to 1000, inside the signed 32 bit range GraphQL
  allows and positive, so a field that expects a count or a size accepts it.
- ``Float``: a count from 0 to 99999 divided by 100, which is one correctly
  rounded division, so the value never depends on how a version prints a float.
- ``Boolean``: one draw of ``below(2)``.
"""

from __future__ import annotations

import re
from collections.abc import Callable, Iterable, Iterator, Mapping
from dataclasses import dataclass
from types import MappingProxyType
from typing import Any

from pytest_graphql._core.factory.rng import DeterministicRandom

_HEX = "0123456789abcdef"

#: The fake of each scalar the GraphQL specification defines.
BUILTIN_FAKES: Mapping[str, Callable[[DeterministicRandom], Any]] = MappingProxyType(
    {
        "String": lambda rng: rng.sample_string(8),
        "ID": lambda rng: rng.sample_string(12, _HEX),
        "Int": lambda rng: 1 + rng.below(1000),
        "Float": lambda rng: rng.below(100_000) / 100,
        "Boolean": lambda rng: rng.below(2) == 1,
    }
)

_GRAPHQL_NAME = re.compile(r"[_A-Za-z][_0-9A-Za-z]*")


@dataclass(frozen=True)
class ScalarSpec:
    """How the package handles one custom scalar.

    ``fake`` receives a ``DeterministicRandom`` and never ``random.Random``,
    because a caller handed the standard generator could produce a value that
    is not reproducible.
    """

    name: str
    serialize: Callable[[Any], Any]
    fake: Callable[[DeterministicRandom], Any]
    parse: Callable[[Any], Any] | None = None

    def __post_init__(self) -> None:
        if not isinstance(self.name, str):
            raise TypeError(
                f"a scalar name must be a str, got {type(self.name).__name__}."
            )
        if not _GRAPHQL_NAME.fullmatch(self.name) or self.name.startswith("__"):
            raise ValueError(
                f"{self.name!r} is not a GraphQL name.\n"
                "  A name starts with a letter or an underscore, followed by "
                "letters, digits or underscores, and never starts with '__'."
            )
        if self.name in BUILTIN_FAKES:
            raise ValueError(
                f"{self.name!r} is a built-in scalar and cannot be registered.\n"
                "  Built-in scalars are generated by the package. Register a "
                "custom scalar, or pass a value for the field."
            )
        for label, value in (("serialize", self.serialize), ("fake", self.fake)):
            if not callable(value):
                raise TypeError(
                    f"ScalarSpec {label} must be callable, got {type(value).__name__}."
                )
        if self.parse is not None and not callable(self.parse):
            raise TypeError(
                "ScalarSpec parse must be callable or None, got "
                f"{type(self.parse).__name__}."
            )


class ScalarRegistry:
    """The custom scalars a client knows, by name."""

    __slots__ = ("_specs",)

    def __init__(self, specs: Iterable[ScalarSpec] = ()) -> None:
        self._specs: dict[str, ScalarSpec] = {}
        for spec in specs:
            self.register(spec)

    def register(self, spec: ScalarSpec, *, replace: bool = False) -> None:
        """Add ``spec``. A name that is already registered is refused.

        Two registrations of one name are usually two plugins that disagree, so
        the second is an error unless the caller says it means to replace.
        """
        if not isinstance(spec, ScalarSpec):
            raise TypeError(
                f"register() needs a ScalarSpec, got {type(spec).__name__}."
            )
        if spec.name in self._specs and not replace:
            raise ValueError(
                f"scalar {spec.name!r} is already registered.\n"
                "  Pass replace=True to swap it for this one."
            )
        self._specs[spec.name] = spec

    def get(self, name: str) -> ScalarSpec | None:
        """The spec registered under ``name``, or ``None``."""
        return self._specs.get(name)

    def parsers(self) -> dict[str, Callable[[Any], Any]]:
        """A snapshot of ``name -> parse`` for every spec that decodes."""
        return {
            name: spec.parse
            for name, spec in self._specs.items()
            if spec.parse is not None
        }

    def __contains__(self, name: object) -> bool:
        return name in self._specs

    def __iter__(self) -> Iterator[str]:
        return iter(sorted(self._specs))

    def __len__(self) -> int:
        return len(self._specs)

    def __repr__(self) -> str:
        return f"ScalarRegistry({', '.join(self)})"
